library(dataaimsr)

with_mock_dir("Correct structure methods", {
  test_that("Correct structure", {
    # regular monitoring data
    wa <- aims_data("weather", filters = w_filters, api_key = my_api_key)
    sa <- aims_data("temp_loggers", filters = s_filters,
                          api_key = my_api_key)
    # summary data
    ss <- aims_data("temp_loggers", api_key = my_api_key,
                       summary = "summary-by-series")
    sd <- aims_data("temp_loggers", api_key = my_api_key,
                       summary = "summary-by-deployment")
    expect_output(expect_is(summary(wa), "list"))
    expect_output(expect_is(summary(sa), "list"))
    expect_output(expect_is(summary(ss), "list"))
    expect_output(expect_is(summary(sd), "list"))
    expect_output(print(wa))
    expect_output(print(sa))
    expect_output(print(ss))
    expect_output(print(sd))
    expect_s3_class(head(wa), "aimsdf")
    expect_is(head(wa), "data.frame")
    expect_s3_class(head(sa), "aimsdf")
    expect_is(head(sa), "data.frame")
    expect_s3_class(head(ss), "aimsdf")
    expect_is(head(ss), "data.frame")
    expect_s3_class(head(sd), "aimsdf")
    expect_is(head(sd), "data.frame")
    expect_s3_class(tail(wa), "aimsdf")
    expect_is(tail(wa), "data.frame")
    expect_s3_class(tail(sa), "aimsdf")
    expect_is(tail(sa), "data.frame")
    expect_s3_class(tail(ss), "aimsdf")
    expect_is(tail(ss), "data.frame")
    expect_s3_class(tail(sd), "aimsdf")
    expect_is(tail(sd), "data.frame")
    a_ <- plot(wa, ptype = "map")
    b_ <- plot(wa, ptype = "time_series")
    c_ <- plot(ss, ptype = "map")
    d_ <- plot(sd, ptype = "time_series")
    expect_error(plot(wa))
    expect_error(plot(sa))
    expect_error(plot(ss))
    expect_error(plot(sd))
    expect_visible(plot(wa, ptype = "map"))
    expect_message(expect_visible(plot(wa, ptype = "time_series")))
    expect_visible(plot(wa, ptype = "time_series",
                        pars = "Air Temperature"))
    expect_visible(plot(sa, ptype = "map"))
    expect_message(expect_visible(plot(sa, ptype = "time_series")))
    expect_visible(plot(sa, ptype = "time_series",
                        pars = "Air Temperature"))
    expect_visible(plot(ss, ptype = "map"))
    expect_visible(plot(sd, ptype = "map"))
    expect_message(expect_visible(plot(ss, ptype = "time_series")))
    expect_message(expect_visible(plot(sd, ptype = "time_series")))
    expect_is(a_, "ggplot")
    expect_is(b_, "ggplot")
    expect_is(c_, "ggplot")
    expect_is(d_, "ggplot")
  })
})
