structure(list(url = "https://api.aims.gov.au/data-v2.0/10.25845/5c09bf93f315d/wrong", 
    status_code = 403L, headers = structure(list(date = "Fri, 19 May 2023 03:36:12 GMT", 
        `content-type` = "application/json", `content-length` = "42", 
        `x-amzn-requestid` = "fd777f58-dedd-4cd9-b280-aedfcee9b141", 
        `x-amzn-errortype` = "MissingAuthenticationTokenException", 
        `x-amz-apigw-id` = "FJo6_FssSwMF-Ig="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 403L, version = "HTTP/2", 
        headers = structure(list(date = "Fri, 19 May 2023 03:36:12 GMT", 
            `content-type` = "application/json", `content-length` = "42", 
            `x-amzn-requestid` = "fd777f58-dedd-4cd9-b280-aedfcee9b141", 
            `x-amzn-errortype` = "MissingAuthenticationTokenException", 
            `x-amz-apigw-id` = "FJo6_FssSwMF-Ig="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"message\":\"Missing Authentication Token\"}"), 
    date = structure(1684467372, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.4e-05, 
    connect = 0, pretransfer = 0.000249, starttransfer = 0.060357, 
    total = 0.060455)), class = "response")
