structure(list(url = "https://api.aims.gov.au/data-v2.0/10.25845/5c09bf93f315d/wrong", 
    status_code = 403L, headers = structure(list(date = "Fri, 19 May 2023 05:57:03 GMT", 
        `content-type` = "application/json", `content-length` = "42", 
        `x-amzn-requestid` = "64a48c61-4f38-4100-b948-d50d1654c7c9", 
        `x-amzn-errortype` = "MissingAuthenticationTokenException", 
        `x-amz-apigw-id` = "FJ9jhG4dSwMF13A="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 403L, version = "HTTP/2", 
        headers = structure(list(date = "Fri, 19 May 2023 05:57:03 GMT", 
            `content-type` = "application/json", `content-length` = "42", 
            `x-amzn-requestid` = "64a48c61-4f38-4100-b948-d50d1654c7c9", 
            `x-amzn-errortype` = "MissingAuthenticationTokenException", 
            `x-amz-apigw-id` = "FJ9jhG4dSwMF13A="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"message\":\"Missing Authentication Token\"}"), 
    date = structure(1684475823, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 7.1e-05, 
    connect = 0, pretransfer = 0.000223, starttransfer = 0.066316, 
    total = 0.067288)), class = "response")
