structure(list(url = "https://api.aims.gov.au/data-v2.0/10.25845/5c09bf93f315d/wrong", 
    status_code = 403L, headers = structure(list(date = "Wed, 06 Jul 2022 07:47:24 GMT", 
        `content-type` = "application/json", `content-length` = "42", 
        `x-amzn-requestid` = "fb18ea03-50b3-40e4-930a-378a22ab0a99", 
        `x-amzn-errortype` = "MissingAuthenticationTokenException", 
        `x-amz-apigw-id` = "U1ah_HyuSwMFmgA="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 403L, version = "HTTP/2", 
        headers = structure(list(date = "Wed, 06 Jul 2022 07:47:24 GMT", 
            `content-type` = "application/json", `content-length` = "42", 
            `x-amzn-requestid` = "fb18ea03-50b3-40e4-930a-378a22ab0a99", 
            `x-amzn-errortype` = "MissingAuthenticationTokenException", 
            `x-amz-apigw-id` = "U1ah_HyuSwMFmgA="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"message\":\"Missing Authentication Token\"}"), 
    date = structure(1657093644, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 6e-05, 
    connect = 6e-05, pretransfer = 0.000441, starttransfer = 0.05865, 
    total = 0.058695)), class = "response")
