structure(list(url = "https://api.aims.gov.au/data-v2.0/10.25845/5c09bf93f315d/wrong", 
    status_code = 403L, headers = structure(list(date = "Thu, 18 Mar 2021 10:10:53 GMT", 
        `content-type` = "application/json", `content-length` = "42", 
        `x-amzn-requestid` = "68e43d11-d481-4175-8f0d-11708ba0d73d", 
        `x-amzn-errortype` = "MissingAuthenticationTokenException", 
        `x-amz-apigw-id` = "cYMPFGTCywMFQxw="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 403L, version = "HTTP/2", 
        headers = structure(list(date = "Thu, 18 Mar 2021 10:10:53 GMT", 
            `content-type` = "application/json", `content-length` = "42", 
            `x-amzn-requestid` = "68e43d11-d481-4175-8f0d-11708ba0d73d", 
            `x-amzn-errortype` = "MissingAuthenticationTokenException", 
            `x-amz-apigw-id` = "cYMPFGTCywMFQxw="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"message\":\"Missing Authentication Token\"}"), 
    date = structure(1616062253, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.6e-05, 
    connect = 2.8e-05, pretransfer = 9e-05, starttransfer = 0.112679, 
    total = 0.112696)), class = "response")
