structure(list(url = "https://api.aims.gov.au/data-v2.0/10.25845/5c09bf93f315d/wrong", 
    status_code = 403L, headers = structure(list(date = "Wed, 31 May 2023 05:25:02 GMT", 
        `content-type` = "application/json", `content-length` = "42", 
        `x-amzn-requestid` = "8ff58743-9899-440f-aba3-ccab58685337", 
        `x-amzn-errortype` = "MissingAuthenticationTokenException", 
        `x-amz-apigw-id` = "FxcHUEG9SwMFhNA="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 403L, version = "HTTP/2", 
        headers = structure(list(date = "Wed, 31 May 2023 05:25:02 GMT", 
            `content-type` = "application/json", `content-length` = "42", 
            `x-amzn-requestid` = "8ff58743-9899-440f-aba3-ccab58685337", 
            `x-amzn-errortype` = "MissingAuthenticationTokenException", 
            `x-amz-apigw-id` = "FxcHUEG9SwMFhNA="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"message\":\"Missing Authentication Token\"}"), 
    date = structure(1685510702, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.8e-05, 
    connect = 0, pretransfer = 0.000288, starttransfer = 0.064454, 
    total = 0.064715)), class = "response")
